#Library System Configuration
#Thu Apr 09 17:59:18 ICT 2026
finePerDay=5000.0
maxBorrowDays=14
# SQL Server: thay TEN_MAY_CHU, TEN_INSTANCE, ten_database cho phu hop
# LUU Y: Trong file .properties, phai dung 2 dau gach cheo nguoc (\\) hoac dung port :1433
# Vi du 1 (Dung instance name, phai co \\): jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=LibraryDB;encrypt=false;integratedSecurity=false;user=sa;password=MatKhausa
# Vi du 2 (Dung port truc tiep, khong lo bi loi dau gach): jdbc:sqlserver://127.0.0.1:1433;databaseName=LibraryDB;encrypt=false;integratedSecurity=false;user=sa;password=MatKhausa
# Kich hoat MSSQL cho ung dung:
dbUrl=jdbc:sqlserver://127.0.0.1:1433;databaseName=LibraryDB;encrypt=false;integratedSecurity=false;user=sa;password=dpct1272007@K